/*
 * This file is part of the Tensorflow Micropython Examples Project.
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2022 Michael O'Cleirigh
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
#ifndef __LIB_TF_OB_RESOLVERS_H_
#define __LIB_TF_OB_RESOLVERS_H_

#ifdef __cplusplus
extern "C" {
#endif

// Values defined here can be overridden by your own config file as
// make -MICROLITE_TFLM_OPS_CONFIG_FILE="my_tflm_ops_config.h"
// or specify in the mpconfigboard.h file
#if defined(MICROLITE_TFLM_OPS_CONFIG_FILE)
#include MICROLITE_TFLM_OPS_CONFIG_FILE
#endif

/*
 This __COUNTER__ is a GNU Compiler preproccessor extension where each time its called it will increment.

 It allows us to not count how many tflm op's we enable.  Instead the counter is incremented each time an op 
 is enabled.

 Then at the end we turn the final total into a constant and use that for the MicroMutableOpResolver's size.
 */
#ifndef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#ifndef MICROLITE_OP_ABS
#define MICROLITE_OP_ABS (1)
#endif

#if MICROLITE_OP_ABS == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_ADD
#define MICROLITE_OP_ADD (1)
#endif

#if MICROLITE_OP_ADD == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_ADD_N
#define MICROLITE_OP_ADD_N (1)
#endif

#if MICROLITE_OP_ADD_N == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_ARG_MAX
#define MICROLITE_OP_ARG_MAX (1)
#endif

#if MICROLITE_OP_ARG_MAX == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_ARG_MIN
#define MICROLITE_OP_ARG_MIN (1)
#endif

#if MICROLITE_OP_ARG_MIN == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_AVERAGE_POOL_2D
#define MICROLITE_OP_AVERAGE_POOL_2D (1)
#endif

#if MICROLITE_OP_AVERAGE_POOL_2D == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_BATCH_TO_SPACE_ND
#define MICROLITE_OP_BATCH_TO_SPACE_ND (1)
#endif

#if MICROLITE_OP_BATCH_TO_SPACE_ND == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_CAST
#define MICROLITE_OP_CAST (1)
#endif

#if MICROLITE_OP_CAST == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_CEIL
#define MICROLITE_OP_CEIL (1)
#endif

#if MICROLITE_OP_CEIL == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_CIRCULAR_BUFFER
#define MICROLITE_OP_CIRCULAR_BUFFER (1)
#endif

#if MICROLITE_OP_CIRCULAR_BUFFER == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_CONCATENATION
#define MICROLITE_OP_CONCATENATION (1)
#endif

#if MICROLITE_OP_CONCATENATION == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_CONV_2D
#define MICROLITE_OP_CONV_2D (1)
#endif

#if MICROLITE_OP_CONV_2D == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_COS
#define MICROLITE_OP_COS (1)
#endif

#if MICROLITE_OP_COS == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_CUMSUM
#define MICROLITE_OP_CUMSUM   (1)
#endif

#if MICROLITE_OP_CUMSUM   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_DEPTH_TO_SPACE
#define MICROLITE_OP_DEPTH_TO_SPACE (1)
#endif

#if MICROLITE_OP_DEPTH_TO_SPACE == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_DEPTHWISE_CONV_2D
#define MICROLITE_OP_DEPTHWISE_CONV_2D   (1)
#endif

#if MICROLITE_OP_DEPTHWISE_CONV_2D   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_DEQUANTIZE
#define MICROLITE_OP_DEQUANTIZE   (1)
#endif

#if MICROLITE_OP_DEQUANTIZE   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_DETECTION_POSTPROCESS
#define MICROLITE_OP_DETECTION_POSTPROCESS   (1)
#endif

#if MICROLITE_OP_DETECTION_POSTPROCESS   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_ELU
#define MICROLITE_OP_ELU   (1)
#endif

#if MICROLITE_OP_ELU   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_EQUAL
#define MICROLITE_OP_EQUAL   (1)
#endif

#if MICROLITE_OP_EQUAL   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_ETHOSU
#define MICROLITE_OP_ETHOSU   (1)
#endif

#if MICROLITE_OP_ETHOSU   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_EXP
#define MICROLITE_OP_EXP   (1)
#endif

#if MICROLITE_OP_EXP   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_EXPAND_DIMS
#define MICROLITE_OP_EXPAND_DIMS (1)
#endif

#if MICROLITE_OP_EXPAND_DIMS == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_FILL
#define MICROLITE_OP_FILL   (1)
#endif

#if MICROLITE_OP_FILL   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_FLOOR
#define MICROLITE_OP_FLOOR   (1)
#endif

#if MICROLITE_OP_FLOOR   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_FLOOR_DIV
#define MICROLITE_OP_FLOOR_DIV   (1)
#endif

#if MICROLITE_OP_FLOOR_DIV   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_FLOOR_MOD
#define MICROLITE_OP_FLOOR_MOD   (1)
#endif

#if MICROLITE_OP_FLOOR_MOD   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_FULLY_CONNECTED
#define MICROLITE_OP_FULLY_CONNECTED   (1)
#endif

#if MICROLITE_OP_FULLY_CONNECTED   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_GATHER
#define MICROLITE_OP_GATHER   (1)
#endif

#if MICROLITE_OP_GATHER   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_GATHER_ND
#define MICROLITE_OP_GATHER_ND   (1)
#endif

#if MICROLITE_OP_GATHER_ND   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_GREATER
#define MICROLITE_OP_GREATER   (1)
#endif

#if MICROLITE_OP_GREATER   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_GREATER_EQUAL
#define MICROLITE_OP_GREATER_EQUAL   (1)
#endif

#if MICROLITE_OP_GREATER_EQUAL   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_HARD_SWISH
#define MICROLITE_OP_HARD_SWISH   (1)
#endif

#if MICROLITE_OP_HARD_SWISH   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_IF
#define MICROLITE_OP_IF   (1)
#endif

#if MICROLITE_OP_IF   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_L2_NORMALIZATION
#define MICROLITE_OP_L2_NORMALIZATION   (1)
#endif

#if MICROLITE_OP_L2_NORMALIZATION   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_L2_POOL_2D
#define MICROLITE_OP_L2_POOL_2D   (1)
#endif

#if MICROLITE_OP_L2_POOL_2D   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_LEAKY_RELU
#define MICROLITE_OP_LEAKY_RELU   (1)
#endif

#if MICROLITE_OP_LEAKY_RELU   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_LESS
#define MICROLITE_OP_LESS   (1)
#endif

#if MICROLITE_OP_LESS   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_LESS_EQUAL
#define MICROLITE_OP_LESS_EQUAL   (1)
#endif

#if MICROLITE_OP_LESS_EQUAL   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_LOG
#define MICROLITE_OP_LOG   (1)
#endif

#if MICROLITE_OP_LOG   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_LOGICAL_AND
#define MICROLITE_OP_LOGICAL_AND (1)
#endif

#if MICROLITE_OP_LOGICAL_AND == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_LOGICAL_NOT
#define MICROLITE_OP_LOGICAL_NOT   (1)
#endif

#if MICROLITE_OP_LOGICAL_NOT   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_LOGICAL_OR
#define MICROLITE_OP_LOGICAL_OR   (1)
#endif

#if MICROLITE_OP_LOGICAL_OR   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_LOGISTIC
#define MICROLITE_OP_LOGISTIC   (1)
#endif

#if MICROLITE_OP_LOGISTIC   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_MAXIMUM
#define MICROLITE_OP_MAXIMUM   (1)
#endif

#if MICROLITE_OP_MAXIMUM   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_MAX_POOL_2D
#define MICROLITE_OP_MAX_POOL_2D   (1)
#endif

#if MICROLITE_OP_MAX_POOL_2D   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_MEAN
#define MICROLITE_OP_MEAN   (1)
#endif

#if MICROLITE_OP_MEAN   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_MINIMUM
#define MICROLITE_OP_MINIMUM   (1)
#endif

#if MICROLITE_OP_MINIMUM   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_MUL
#define MICROLITE_OP_MUL   (1)
#endif

#if MICROLITE_OP_MUL   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_NEG
#define MICROLITE_OP_NEG   (1)
#endif

#if MICROLITE_OP_NEG   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_NOT_EQUAL
#define MICROLITE_OP_NOT_EQUAL   (1)
#endif

#if MICROLITE_OP_NOT_EQUAL   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_PACK
#define MICROLITE_OP_PACK   (1)
#endif

#if MICROLITE_OP_PACK   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_PAD
#define MICROLITE_OP_PAD   (1)
#endif

#if MICROLITE_OP_PAD   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_PADV2
#define MICROLITE_OP_PADV2   (1)
#endif

#if MICROLITE_OP_PADV2   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_PRELU
#define MICROLITE_OP_PRELU   (1)
#endif

#if MICROLITE_OP_PRELU   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_QUANTIZE
#define MICROLITE_OP_QUANTIZE   (1)
#endif

#if MICROLITE_OP_QUANTIZE   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_REDUCE_MAX
#define MICROLITE_OP_REDUCE_MAX   (1)
#endif

#if MICROLITE_OP_REDUCE_MAX   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_RELU
#define MICROLITE_OP_RELU   (1)
#endif

#if MICROLITE_OP_RELU   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_RELU6
#define MICROLITE_OP_RELU6   (1)
#endif

#if MICROLITE_OP_RELU6   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_RESHAPE
#define MICROLITE_OP_RESHAPE   (1)
#endif

#if MICROLITE_OP_RESHAPE   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_RESIZE_BILINEAR
#define MICROLITE_OP_RESIZE_BILINEAR   (1)
#endif

#if MICROLITE_OP_RESIZE_BILINEAR   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_RESIZE_NEAREST_NEIGHBOR
#define MICROLITE_OP_RESIZE_NEAREST_NEIGHBOR   (1)
#endif

#if MICROLITE_OP_RESIZE_NEAREST_NEIGHBOR   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_ROUND
#define MICROLITE_OP_ROUND   (1)
#endif

#if MICROLITE_OP_ROUND   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_RSQRT
#define MICROLITE_OP_RSQRT   (1)
#endif

#if MICROLITE_OP_RSQRT   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SHAPE
#define MICROLITE_OP_SHAPE   (1)
#endif

#if MICROLITE_OP_SHAPE   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SIN
#define MICROLITE_OP_SIN   (1)
#endif

#if MICROLITE_OP_SIN   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SOFTMAX
#define MICROLITE_OP_SOFTMAX   (1)
#endif

#if MICROLITE_OP_SOFTMAX   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SPACE_TO_BATCH_ND
#define MICROLITE_OP_SPACE_TO_BATCH_ND   (1)
#endif

#if MICROLITE_OP_SPACE_TO_BATCH_ND   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SPACE_TO_DEPTH
#define MICROLITE_OP_SPACE_TO_DEPTH   (1)
#endif

#if MICROLITE_OP_SPACE_TO_DEPTH   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SPLIT
#define MICROLITE_OP_SPLIT   (1)
#endif

#if MICROLITE_OP_SPLIT   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SPLIT_V
#define MICROLITE_OP_SPLIT_V   (1)
#endif

#if MICROLITE_OP_SPLIT_V   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SQUEEZE
#define MICROLITE_OP_SQUEEZE   (1)
#endif

#if MICROLITE_OP_SQUEEZE   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SQRT
#define MICROLITE_OP_SQRT   (1)
#endif

#if MICROLITE_OP_SQRT   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SQUARE
#define MICROLITE_OP_SQUARE   (1)
#endif

#if MICROLITE_OP_SQUARE   == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_STRIDED_SLICE
#define MICROLITE_OP_STRIDED_SLICE (1)
#endif

#if MICROLITE_OP_STRIDED_SLICE == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SUB
#define MICROLITE_OP_SUB (1)
#endif

#if MICROLITE_OP_SUB == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SVDF
#define MICROLITE_OP_SVDF (1)
#endif

#if MICROLITE_OP_SVDF == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_TANH
#define MICROLITE_OP_TANH (1)
#endif

#if MICROLITE_OP_TANH == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_TRANSPOSE_CONV
#define MICROLITE_OP_TRANSPOSE_CONV (1)
#endif

#if MICROLITE_OP_TRANSPOSE_CONV == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_TRANSPOSE
#define MICROLITE_OP_TRANSPOSE (1)
#endif

#if MICROLITE_OP_TRANSPOSE == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_UNPACK
#define MICROLITE_OP_UNPACK (1)
#endif

#if MICROLITE_OP_UNPACK == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_ZEROS_LIKE
#define MICROLITE_OP_ZEROS_LIKE (1)
#endif

#if MICROLITE_OP_ZEROS_LIKE == 1

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif


#ifndef MICROLITE_TOTAL
#define MICROLITE_TOTAL MICROLITE_TOTAL_COUNTER

const int MICROLITE_TOTAL_OPS = MICROLITE_TOTAL;

#endif

int libtf_op_resolver_init(void *op_resolver);

#ifdef __cplusplus
}
#endif

#endif // __LIB_TF_OB_RESOLVERS_H_
