/*
 * This file is part of the Tensorflow Micropython Examples Project.
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2021 Michael O'Cleirigh
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
#ifndef __LIB_TF_OB_RESOLVERS_H_
#define __LIB_TF_OB_RESOLVERS_H_

#ifdef __cplusplus
extern "C" {
#endif

#ifndef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#ifndef MICROLITE_OP_ABS
#define MICROLITE_OP_ABS (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_ADD
#define MICROLITE_OP_ADD (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_ADD_N
#define MICROLITE_OP_ADD_N (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_ARG_MAX
#define MICROLITE_OP_ARG_MAX (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_ARG_MIN
#define MICROLITE_OP_ARG_MIN (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_AVERAGE_POOL_2D
#define MICROLITE_OP_AVERAGE_POOL_2D (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_BATCH_TO_SPACE_ND
#define MICROLITE_OP_BATCH_TO_SPACE_ND (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_CAST
#define MICROLITE_OP_CAST (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_CEIL
#define MICROLITE_OP_CEIL (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_CIRCULAR_BUFFER
#define MICROLITE_OP_CIRCULAR_BUFFER (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_CONCATENATION
#define MICROLITE_OP_CONCATENATION (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_CONV_2D
#define MICROLITE_OP_CONV_2D (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_COS
#define MICROLITE_OP_COS (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_CUMSUM
#define MICROLITE_OP_CUMSUM   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_DEPTH_TO_SPACE
#define MICROLITE_OP_DEPTH_TO_SPACE (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_DEPTHWISE_CONV_2D
#define MICROLITE_OP_DEPTHWISE_CONV_2D   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_DEQUANTIZE
#define MICROLITE_OP_DEQUANTIZE   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_DETECTION_POSTPROCESS
#define MICROLITE_OP_DETECTION_POSTPROCESS   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_ELU
#define MICROLITE_OP_ELU   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_EQUAL
#define MICROLITE_OP_EQUAL   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_ETHOSU
#define MICROLITE_OP_ETHOSU   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_EXP
#define MICROLITE_OP_EXP   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_EXPAND_DIMS
#define MICROLITE_OP_EXPAND_DIMS (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_FILL
#define MICROLITE_OP_FILL   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_FLOOR
#define MICROLITE_OP_FLOOR   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_FLOOR_DIV
#define MICROLITE_OP_FLOOR_DIV   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_FLOOR_MOD
#define MICROLITE_OP_FLOOR_MOD   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_FULLY_CONNECTED
#define MICROLITE_OP_FULLY_CONNECTED   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_GATHER
#define MICROLITE_OP_GATHER   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_GATHER_ND
#define MICROLITE_OP_GATHER_ND   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_GREATER
#define MICROLITE_OP_GREATER   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_GREATER_EQUAL
#define MICROLITE_OP_GREATER_EQUAL   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_HARD_SWISH
#define MICROLITE_OP_HARD_SWISH   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_IF
#define MICROLITE_OP_IF   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_L2_NORMALIZATION
#define MICROLITE_OP_L2_NORMALIZATION   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_L2_POOL_2D
#define MICROLITE_OP_L2_POOL_2D   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_LEAKY_RELU
#define MICROLITE_OP_LEAKY_RELU   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_LESS
#define MICROLITE_OP_LESS   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_LESS_EQUAL
#define MICROLITE_OP_LESS_EQUAL   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_LOG
#define MICROLITE_OP_LOG   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_LOGICAL_AND
#define MICROLITE_OP_LOGICAL_AND (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_LOGICAL_NOT
#define MICROLITE_OP_LOGICAL_NOT   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_LOGICAL_OR
#define MICROLITE_OP_LOGICAL_OR   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_LOGISTIC
#define MICROLITE_OP_LOGISTIC   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_MAXIMUM
#define MICROLITE_OP_MAXIMUM   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_MAX_POOL_2D
#define MICROLITE_OP_MAX_POOL_2D   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_MEAN
#define MICROLITE_OP_MEAN   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_MINIMUM
#define MICROLITE_OP_MINIMUM   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_MUL
#define MICROLITE_OP_MUL   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif


#endif

#ifndef MICROLITE_OP_NEG
#define MICROLITE_OP_NEG   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_NOT_EQUAL
#define MICROLITE_OP_NOT_EQUAL   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_PACK
#define MICROLITE_OP_PACK   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_PAD
#define MICROLITE_OP_PAD   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_PADV2
#define MICROLITE_OP_PADV2   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_PRELU
#define MICROLITE_OP_PRELU   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_QUANTIZE
#define MICROLITE_OP_QUANTIZE   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_REDUCE_MAX
#define MICROLITE_OP_REDUCE_MAX   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_RELU
#define MICROLITE_OP_RELU   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_RELU6
#define MICROLITE_OP_RELU6   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_RESHAPE
#define MICROLITE_OP_RESHAPE   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_RESIZE_BILINEAR
#define MICROLITE_OP_RESIZE_BILINEAR   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_RESIZE_NEAREST_NEIGHBOR
#define MICROLITE_OP_RESIZE_NEAREST_NEIGHBOR   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_ROUND
#define MICROLITE_OP_ROUND   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_RSQRT
#define MICROLITE_OP_RSQRT   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SHAPE
#define MICROLITE_OP_SHAPE   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SIN
#define MICROLITE_OP_SIN   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SOFTMAX
#define MICROLITE_OP_SOFTMAX   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SPACE_TO_BATCH_ND
#define MICROLITE_OP_SPACE_TO_BATCH_ND   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SPACE_TO_DEPTH
#define MICROLITE_OP_SPACE_TO_DEPTH   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SPLIT
#define MICROLITE_OP_SPLIT   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SPLIT_V
#define MICROLITE_OP_SPLIT_V   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SQUEEZE
#define MICROLITE_OP_SQUEEZE   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SQRT
#define MICROLITE_OP_SQRT   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SQUARE
#define MICROLITE_OP_SQUARE   (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_STRIDED_SLICE
#define MICROLITE_OP_STRIDED_SLICE (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SUB
#define MICROLITE_OP_SUB (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_SVDF
#define MICROLITE_OP_SVDF (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_TANH
#define MICROLITE_OP_TANH (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_TRANSPOSE_CONV
#define MICROLITE_OP_TRANSPOSE_CONV (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_TRANSPOSE
#define MICROLITE_OP_TRANSPOSE (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_UNPACK
#define MICROLITE_OP_UNPACK (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif

#ifndef MICROLITE_OP_ZEROS_LIKE
#define MICROLITE_OP_ZEROS_LIKE (0)

#if MICROLITE_TOTAL_COUNTER
#undef MICROLITE_TOTAL_COUNTER
#define MICROLITE_TOTAL_COUNTER __COUNTER__
#endif

#endif


#ifndef MICROLITE_TOTAL
#define MICROLITE_TOTAL MICROLITE_TOTAL_COUNTER

const int MICROLITE_TOTAL_OPS = MICROLITE_TOTAL;

#endif

int libtf_op_resolver_init(void *op_resolver);

#ifdef __cplusplus
}
#endif

#endif // __LIB_TF_OB_RESOLVERS_H_
